# Generated by Django 4.1.5 on 2023-05-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_crud_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='crud_Member',
        ),
    ]
