# Generated by Django 4.1.5 on 2023-05-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_delete_crud_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=40)),
                ('typeofcar', models.CharField(blank=True, max_length=10)),
                ('speed', models.TextField(max_length=255)),
                ('startdate', models.DateField(verbose_name='%m/%d/%Y')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
