# Generated by Django 4.1.5 on 2023-05-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_delete_ajax_delete_csvupload_delete_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartbl',
            new_name='Car',
        ),
    ]
